development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:0f6640754f99654447ee177a2888a815@spinyfin.redistogo.com:11819/
  channel_prefix: testChat_production
